print("--------CALCULATOR--------")
first_num_txt = input("enter your first number : ")
first_num = float(first_num_txt)
second_num_txt = input("enter your second number : ")
second_num = float(second_num_txt)

print(f"addition : {first_num + second_num}")
print(f"difference : {first_num - second_num}")
print(f"Product : {first_num * second_num}")
print(f"Quotient : {first_num / second_num}")